language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - android-26
    - extra-android-m2repository
    - build-tools-26.0.1

    # The SDK version used to compile your project
	
before_install:
    - chmod +x gradlew
script:
    - ./gradlew build connectedCheck